### ISSUE TITLE
[question] Why not build from upstream?

### ISSUE THREAD

**Issue by uilianries** [int010h/conan-luajit#5]
Hi!

I'm curious why your recipe is built from your fork and not from the upstream?

Maybe you could contribute your patch to the upstream and build this Conan package using the upstream sources.

**Comment by int010h** [comment]
Hi, because upstream doesn't have CMake build scripts and probably won't ever have.
I guess luajit repo on github is just a mirror - a lot of PRs are open, but don't getting merged for years. So I'm not sure if the project is still actively developed or maintained.
And I didn't had enough time to investigate further, just wanted to use the package in personal project, so decided to fork.

**Comment by uilianries** [comment]
Fair enough! :+1: 

Thanks for answering this.
